CREATE DATABASE db_pets;
USE db_pets;

CREATE TABLE Usuario (
Id INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(100) NOT NULL,
Email VARCHAR(100) NOT NULL,
Senha VARCHAR(40) NOT NULL
);

CREATE TABLE Produto (
Id INT PRIMARY KEY AUTO_INCREMENT,
Nome VARCHAR(100) NOT NULL,
Descricao TEXT NOT NULL,
Preco DECIMAL(7,2) NOT NULL,
Qtd INT NOT NULL
);

SELECT * FROM Usuario;
SELECT * FROM Produto;